# Generated by Django 5.2.15 on 2026-06-12 16:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.CharField(blank=True, max_length=256, null=True)),
                ('google_refresh_token', models.TextField(blank=True, null=True)),
                ('buzz_token', models.TextField(blank=True, null=True)),
                ('veracross_cookies', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='buzz', max_length=32)),
                ('external_id', models.CharField(max_length=256)),
                ('enrollment_id', models.CharField(blank=True, default='', max_length=64)),
                ('course_name', models.CharField(blank=True, default='', max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('item_type', models.CharField(blank=True, default='', max_length=64)),
                ('achieved', models.CharField(blank=True, default='', max_length=64)),
                ('possible', models.CharField(blank=True, default='', max_length=64)),
                ('letter', models.CharField(blank=True, default='', max_length=16)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'grades',
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uq_grade_source_extid')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=256, null=True)),
                ('course_name', models.CharField(blank=True, default='', max_length=256)),
                ('priority_score', models.IntegerField(default=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'tasks',
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uq_source_extid')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('channel', models.CharField(default='sms', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.task')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
