from django.urls import path

from core import views

urlpatterns = [
    path("", views.index, name="index"),
    path("calendar", views.calendar_page),
    path("chat", views.chat_page),
    path("settings", views.settings_page),
    path("login", views.login_page),
    path("completed", views.completed_page),
    path("announcements", views.announcements_page),
    path("notifications", views.notifications_page),
    path("library", views.library_page),
    path("sync/all", views.sync_all_view),
    path("sync/<str:source>", views.sync_one_view),
    path("api/notifications/test", views.test_notification),
    path("api/gmail/purge-junk", views.purge_gmail_junk_view),
    path("api/tasks", views.api_tasks),
    path("api/announcements", views.api_announcements),
    path("api/news", views.api_news),
    path("api/activity", views.api_activity),
    path("api/tasks/urgent", views.api_urgent),
    path("api/conflicts", views.api_conflicts),
    path("api/library", views.api_library),
    path("api/tasks/<int:task_id>/complete", views.complete_task),
    path("api/status", views.api_status),
    path("api/account", views.api_account),
    path("auth/google", views.auth_google),
    path("auth/google/callback", views.auth_google_cb),
    path("ai/chat", views.ai_chat),
    path("ai/digest", views.ai_digest),
    path("api/settings", views.settings_api),
    path("api/settings/test-login", views.test_logins),
    path("api/admin/credentials", views.admin_credentials_api),
    path("api/notifications/prefs", views.notification_prefs_api),
    path("api/notifications/defaults", views.defaults_prefs),
    path("api/messaging/status", views.api_messaging_status),
    path("sms/incoming", views.sms_incoming),
    path("whatsapp/incoming", views.whatsapp_incoming),
    path("telegram/webhook", views.telegram_webhook),
]
